"""Cognitive layer contracts for context, research, proposal, selection, planning, and evaluation."""

from .context import ContextPackage, assemble_context_package
from .evaluation import EvaluationResult, deterministic_override_reasons, evaluate_outcome
from .planning import PlanArtifact, create_plan, should_plan
from .proposal import ProposalOption, ProposalSet
from .research import (
    EvidenceItem,
    EvidencePack,
    ResearchArtifact,
    ResearchArtifactRecord,
    ResearchArtifactStore,
    ResearchFinding,
    ResearchMemoryHandoffInput,
    ResearchProvenanceValidationError,
    ResearchRequest,
    ResearchResult,
    ResearchSynthesisError,
    ResearchSynthesisRuntimeError,
    ResearchSynthesisValidationError,
    SourceItem,
    build_document_evidence_pack,
    build_research_memory_handoff_input,
    build_research_artifact_record,
    build_research_model_request,
    build_web_evidence_pack,
    collect_document_sources,
    collect_web_sources,
    handoff_persisted_research_record_to_memory,
    handoff_research_to_memory,
    persist_research_artifact,
    run_and_persist_document_research,
    run_and_persist_web_research,
    run_web_research,
    run_document_research,
    should_handoff_research_to_memory,
    synthesize_research,
    synthesize_research_with_runtime,
    validate_research_artifact_record,
    validate_research_provenance,
)
from .selection import SelectionResult

__all__ = [
    "ContextPackage",
    "EvidenceItem",
    "EvidencePack",
    "EvaluationResult",
    "PlanArtifact",
    "ProposalOption",
    "ResearchArtifact",
    "ResearchArtifactRecord",
    "ResearchArtifactStore",
    "ResearchFinding",
    "ResearchMemoryHandoffInput",
    "ResearchProvenanceValidationError",
    "ProposalSet",
    "ResearchRequest",
    "ResearchResult",
    "ResearchSynthesisError",
    "ResearchSynthesisRuntimeError",
    "ResearchSynthesisValidationError",
    "SelectionResult",
    "SourceItem",
    "assemble_context_package",
    "build_document_evidence_pack",
    "build_research_memory_handoff_input",
    "build_research_artifact_record",
    "build_research_model_request",
    "build_web_evidence_pack",
    "collect_document_sources",
    "collect_web_sources",
    "create_plan",
    "deterministic_override_reasons",
    "evaluate_outcome",
    "handoff_persisted_research_record_to_memory",
    "handoff_research_to_memory",
    "persist_research_artifact",
    "run_and_persist_document_research",
    "run_and_persist_web_research",
    "run_document_research",
    "run_web_research",
    "should_handoff_research_to_memory",
    "should_plan",
    "synthesize_research",
    "synthesize_research_with_runtime",
    "validate_research_artifact_record",
    "validate_research_provenance",
]
