"""Infrastructure-owned replaceable plumbing for Jeff."""

from .capability_profiles import CapabilityProfile, CapabilityProfileRegistry
from .contract_runtime import ContractCallRequest, ContractRuntime
from .output_strategies import OutputStrategy
from .purposes import Purpose
from .config import (
    AdapterConfig,
    AdapterRuntimeOptions,
    JeffRuntimeConfig,
    PurposeOverrides,
    ResearchMemoryRuntimeConfig,
    ResearchRuntimeConfig,
    RuntimeDefaults,
    load_runtime_config,
)
from .model_adapters import (
    AdapterRegistry,
    AdapterFactoryConfig,
    AdapterProviderKind,
    FakeModelAdapter,
    ModelAdapter,
    ModelAdapterError,
    ModelAdapterNotFoundError,
    ModelInvocationError,
    ModelInvocationStatus,
    ModelMalformedOutputError,
    ModelProviderHTTPError,
    ModelRequest,
    ModelResponse,
    ModelResponseMode,
    ModelTelemetryEvent,
    ModelTimeoutError,
    ModelTransportError,
    ModelUsage,
    OllamaModelAdapter,
    create_model_adapter,
    telemetry_from_response,
)
from .runtime import (
    InfrastructureServices,
    ModelAdapterRuntimeConfig,
    build_infrastructure_services,
    build_model_adapter_runtime_config,
)

__all__ = [
    "CapabilityProfile",
    "CapabilityProfileRegistry",
    "ContractCallRequest",
    "ContractRuntime",
    "OutputStrategy",
    "Purpose",
    "AdapterConfig",
    "AdapterRegistry",
    "AdapterFactoryConfig",
    "AdapterProviderKind",
    "AdapterRuntimeOptions",
    "FakeModelAdapter",
    "ModelAdapter",
    "InfrastructureServices",
    "JeffRuntimeConfig",
    "ModelAdapterError",
    "ModelAdapterNotFoundError",
    "ModelInvocationError",
    "ModelInvocationStatus",
    "ModelMalformedOutputError",
    "ModelProviderHTTPError",
    "ModelRequest",
    "ModelResponse",
    "ModelResponseMode",
    "ModelAdapterRuntimeConfig",
    "ModelTelemetryEvent",
    "ModelTimeoutError",
    "ModelTransportError",
    "ModelUsage",
    "OllamaModelAdapter",
    "PurposeOverrides",
    "ResearchMemoryRuntimeConfig",
    "ResearchRuntimeConfig",
    "RuntimeDefaults",
    "build_infrastructure_services",
    "build_model_adapter_runtime_config",
    "create_model_adapter",
    "load_runtime_config",
    "telemetry_from_response",
]
