"""Public proposal contract surface."""

from .api import (
    ProposalPipelineFailure,
    ProposalPipelineFailureStage,
    ProposalPipelineResult,
    ProposalPipelineSuccess,
    run_proposal_repair_attempt,
    run_proposal_generation_pipeline,
)
from .contracts import ProposalResult, ProposalResultOption, ProposalType
from .generation import (
    ProposalGenerationPromptBundle,
    ProposalGenerationRawResult,
    ProposalGenerationRequest,
    build_proposal_generation_prompt_bundle,
    invoke_proposal_generation_with_runtime,
    ProposalGenerationRuntimeError,
)
from .input_bundle import (
    ProposalEvidenceSupport,
    ProposalInputBundle,
    ProposalMemorySupport,
    ProposalRequestFrame,
    ProposalScopeFrame,
    ProposalSupportItem,
    ProposalSupportSection,
    ProposalTruthSnapshot,
    ProposalTruthSnapshotItem,
    build_proposal_input_bundle,
    resolve_committed_memory_support_records,
)
from .proposal_generation_bridge import (
    ProposalGenerationBridgeError,
    ProposalGenerationBridgeIssue,
    ProposalGenerationBridgeRequest,
    ProposalGenerationBridgeResult,
    build_and_run_proposal_generation,
)
from .proposal_support_package_consumer import (
    ProposalInputPackage,
    ProposalSupportConsumerError,
    ProposalSupportConsumerIssue,
    ProposalSupportConsumerRequest,
    consume_proposal_support_package,
)
from .parsing import (
    ParsedProposalGenerationResult,
    ParsedProposalOption,
    ProposalGenerationParseError,
    parse_proposal_generation_result,
)
from .operator_records import (
    ProposalAttemptKind,
    ProposalOperatorRecord,
    ProposalPersistedAttempt,
    ProposalRecordStatus,
    ProposalValidationOutcome,
    build_proposal_record_id,
    build_operator_record_from_pipeline_result,
    proposal_record_created_at_now,
    proposal_attempt_from_pipeline_result,
)
from .validation import (
    ProposalGenerationValidationError,
    ProposalValidationIssue,
    validate_proposal_generation_result,
)

__all__ = [
    "ParsedProposalGenerationResult",
    "ParsedProposalOption",
    "ProposalAttemptKind",
    "ProposalGenerationPromptBundle",
    "ProposalGenerationParseError",
    "ProposalGenerationRawResult",
    "ProposalGenerationRequest",
    "ProposalGenerationRuntimeError",
    "ProposalGenerationBridgeError",
    "ProposalGenerationBridgeIssue",
    "ProposalGenerationBridgeRequest",
    "ProposalGenerationBridgeResult",
    "ProposalEvidenceSupport",
    "ProposalInputBundle",
    "ProposalInputPackage",
    "ProposalMemorySupport",
    "ProposalOperatorRecord",
    "ProposalGenerationValidationError",
    "ProposalPipelineFailure",
    "ProposalPipelineFailureStage",
    "ProposalPipelineResult",
    "ProposalPipelineSuccess",
    "ProposalPersistedAttempt",
    "ProposalRecordStatus",
    "ProposalRequestFrame",
    "ProposalResult",
    "ProposalResultOption",
    "ProposalScopeFrame",
    "ProposalSupportConsumerError",
    "ProposalSupportConsumerIssue",
    "ProposalSupportConsumerRequest",
    "ProposalSupportItem",
    "ProposalSupportSection",
    "ProposalType",
    "ProposalValidationIssue",
    "ProposalValidationOutcome",
    "ProposalTruthSnapshot",
    "ProposalTruthSnapshotItem",
    "build_and_run_proposal_generation",
    "build_proposal_input_bundle",
    "resolve_committed_memory_support_records",
    "build_proposal_record_id",
    "build_operator_record_from_pipeline_result",
    "build_proposal_generation_prompt_bundle",
    "consume_proposal_support_package",
    "invoke_proposal_generation_with_runtime",
    "parse_proposal_generation_result",
    "proposal_record_created_at_now",
    "proposal_attempt_from_pipeline_result",
    "run_proposal_generation_pipeline",
    "run_proposal_repair_attempt",
    "validate_proposal_generation_result",
]
